config/routes.rb
Rails.application.routes.draw do
  resources :medicines, only: :index do
    get :autocomplete_medicine_name, on: :collection
  end

  resources :diseases, only: :index do
    get :autocomplete_disease_name, on: :collection
  end

  resources :interventions, only: :index do
    get :autocomplete_intervention_name, on: :collection
  end

  get 'welcome/index'

end

app/models/disease.rb
class Disease < ActiveRecord::Base
end

app/models/intervention.rb
class Intervention < ActiveRecord::Base
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = 'GET'
  end
end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  after_filter :set_access_control_headers

  autocomplete :disease, :name, full: true

  def index
  end
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  after_filter :set_access_control_headers

  autocomplete :intervention, :name, full: true

  def index
    @interventions = Intervention.where('name like ?', "%#{params[:q]}%").limit(100)
    respond_to do |format|
      format.html
      format.json { render json: @interventions }
      format.xml { render xml: @interventions }
    end
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  after_filter :set_access_control_headers

  autocomplete :medicine, :name, full: true

  def index
    @medicines = Medicine.where('name like ?', "%#{params[:q]}%").limit(100)
    respond_to do |format|
      format.html
      format.json { render json: @medicines }
      format.xml { render xml: @medicines }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/diseases/index.html.erb
<h1>Diseases#index</h1>
<p>Find me in app/views/diseases/index.html.erb</p>

app/views/interventions/index.html.erb
<% @interventions.each do |intervention| %>
  <%= div_for intervention do %>
    <%= intervention.code %> <%= intervention.name %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medicines/index.html.erb
<% @medicines.each do |medicine| %>
  <%= div_for medicine do %>
    <%= medicine.code %> <%= medicine.name %>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= form_tag '', method: :get do %>
  <div class="form-group">
    <%= autocomplete_field_tag 'medicine_name', params[:medicine_name] , autocomplete_medicine_name_medicines_path, class: 'form-control' %>
  </div>
<% end %>